FROM golang:1.22-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -o api ./cmd/http/*.go

FROM scratch

WORKDIR /app

COPY --from=builder /app/api .

CMD [ "/app/api" ]